/* Auto-generated by admin.html */
var PRODUCTS_DATA = [
  {
    "name": "фвфывфыв",
    "brand": "Javokhir Attor",
    "category": "floral",
    "theme": "gold",
    "price": "184",
    "volume": "50",
    "notes": "фывфыв",
    "description": "фывфывфвфы",
    "image": null,
    "heroBackground": "#130b00",
    "heroGlowColor": "#c9a84c",
    "ingredients": [],
    "id": "1778175876274"
  },
  {
    "name": "фывфывфыв",
    "brand": "Javokhir Attor",
    "category": "woody",
    "theme": "gold",
    "price": "184",
    "volume": "50",
    "notes": "ффывфыв фывфыв ывф",
    "description": "фвыфыв фывфыв фывфв",
    "image": null,
    "heroBackground": "#130b00",
    "heroGlowColor": "#c9a84c",
    "ingredients": [],
    "id": "1778176444222"
  }
];
